export const LESSON_OBSERVATION_PARAMETERS = [
  "Reviews the previous lesson/content related to the current lesson",
  "States the objective of the current lesson",
  "Demonstrates innovation and creativity in teaching",
  "Quality of introduction: captivating/captures learners interest",
  "Uses appropriate teaching methods",
  "Teaches with lesson documents",
  "Mastery of content",
  "Summarizes the lesson by highlighting the key points",
  "Covers the lesson within the stipulated time (starts/ends on time)",
  "Is the teacher observant?",
  "Discussion and presentation",
  "Able to stimulate learners",
  "Questions are answered accurately",
  "Composure and silence of learners (including SNE)",
  "Moves in class to observe students work",
  "No chorus answers/knowing students by name",
  "Handles schools resources with care and dignity.",
  "The class is tidy, clean and \"lively\"",
  "Uses the correct language (professional, subject, etc)",
  "Ensures neat work presentation, good state of books",
  "Marks learners work",
  "Uses appropriate teaching aids",
  "The design coverage is within the set range",
  "Follows the Dress Code",
  "Creates a friendly and warm learning atmosphere"
];

export const PROFESSIONAL_DOCUMENTS = [
  "Class diary",
  "Lesson Plans",
  "Schemes of Work",
  "Character Formation Chart",
  "Progress Records",
  "Records of Work",
  "Lesson Notes",
  "Curriculum Design",
  "Individual Learner Evaluation"
];

export const WORK_OBSERVATION_PARAMETERS = [
  "Performs assigned duties accurately.",
  "Follows established procedures and protocols.",
  "Completes tasks within the designated timeframe.",
  "Has a clear daily work routine.",
  "Demonstrates attention to details in job performance.",
  "Has certifications where required by Gov. regulations. (N/A for cleaners)",
  "Ensures safety and security protocols are observed.",
  "The workstation is well arranged, clean, neat and organized.",
  "The verbal communication is clear and effective.",
  "The written communication is clear and effective.",
  "Listens attentively to instructions and feedback.",
  "Reacts positively to corrections and criticism.",
  "Works collaboratively with team members to accomplish tasks.",
  "Identifies and addresses challenges effectively.",
  "Seeks assistance when needed.",
  "Handles schools resources with care and dignity.",
  "Anticipates needs and takes proactive measure to address them.",
  "Has a checklist of the tasks to be completed.",
  "Doesn't waste time.",
  "Demonstrates empathy.",
  "Takes initiative to improve processes, procedures, outcomes.",
  "Demonstrates professionalism in behavior, attitude and appearance.",
  "Follows instructions to the letter.",
  "Able to embrace change",
  "Takes pride in his/her work",
  "(for cleaners only) Keeps confidentiality"
];
