export const ROLES = [
  'DIRECTOR',
  'SCHOOL MANAGER',
  'HEAD TEACHER',
  'FINANCE OFFICER',
  'OPERATIONS OFFICER',
  'SECTION HEAD UPPER PRIMARY',
  'SECTION HEAD JUNIOR SCHOOL',
  'SECTION HEAD LOWER PRIMARY',
  'CURRICULUM COORDINATOR',
  'ICT MANAGER',
  'HEADCOOK',
  'DRIVERS SUPERVISOR',
  'CLEANERS SUPERVISOR',
  'HEAD OF PANELS',
  'CLASS TEACHERS',
  'SPECIAL ROLES',
  'ACCOUNTANT',
  'SECRETARY',
  'ICT TECHNICIANS',
  'TEACHERS',
  'COOKS',
  'CLEANERS',
  'DRIVERS',
  'CARETAKERS',
] as const;

export type UserRole = typeof ROLES[number];

export type RoleCategory = 
  | 'TEACHING'
  | 'NON_TEACHING'
  | 'FIRSTLINE_LEADERSHIP'
  | 'INTERMEDIATE_LEADERSHIP'
  | 'SENIOR_LEADERSHIP'
  | 'DIRECTOR';

export const ROLE_HIERARCHY: Record<UserRole, RoleCategory> = {
  'DIRECTOR': 'DIRECTOR',
  'SCHOOL MANAGER': 'SENIOR_LEADERSHIP',
  'HEAD TEACHER': 'SENIOR_LEADERSHIP',
  'FINANCE OFFICER': 'SENIOR_LEADERSHIP',
  'OPERATIONS OFFICER': 'SENIOR_LEADERSHIP',
  'SECTION HEAD UPPER PRIMARY': 'INTERMEDIATE_LEADERSHIP',
  'SECTION HEAD JUNIOR SCHOOL': 'INTERMEDIATE_LEADERSHIP',
  'SECTION HEAD LOWER PRIMARY': 'INTERMEDIATE_LEADERSHIP',
  'CURRICULUM COORDINATOR': 'INTERMEDIATE_LEADERSHIP',
  'ICT MANAGER': 'INTERMEDIATE_LEADERSHIP',
  'HEADCOOK': 'INTERMEDIATE_LEADERSHIP',
  'DRIVERS SUPERVISOR': 'INTERMEDIATE_LEADERSHIP',
  'CLEANERS SUPERVISOR': 'INTERMEDIATE_LEADERSHIP',
  'HEAD OF PANELS': 'FIRSTLINE_LEADERSHIP',
  'CLASS TEACHERS': 'FIRSTLINE_LEADERSHIP',
  'SPECIAL ROLES': 'FIRSTLINE_LEADERSHIP',
  'TEACHERS': 'TEACHING',
  'ACCOUNTANT': 'NON_TEACHING',
  'SECRETARY': 'NON_TEACHING',
  'ICT TECHNICIANS': 'NON_TEACHING',
  'COOKS': 'NON_TEACHING',
  'CLEANERS': 'NON_TEACHING',
  'DRIVERS': 'NON_TEACHING',
  'CARETAKERS': 'NON_TEACHING',
};

export const getRoleCategory = (role: string): RoleCategory => {
  const normalizedRole = role?.toUpperCase()?.trim();
  
  // Direct match
  if (ROLE_HIERARCHY[normalizedRole as UserRole]) {
    return ROLE_HIERARCHY[normalizedRole as UserRole];
  }

  // Handle singular/plural mismatches
  if (normalizedRole === 'TEACHER') return 'TEACHING';
  if (normalizedRole === 'COOK') return 'NON_TEACHING';
  if (normalizedRole === 'DRIVER') return 'NON_TEACHING';
  if (normalizedRole === 'CLEANER') return 'NON_TEACHING';
  if (normalizedRole === 'CARETAKER') return 'NON_TEACHING';
  if (normalizedRole === 'ICT TECHNICIAN') return 'NON_TEACHING';
  if (normalizedRole === 'CLASS TEACHER') return 'FIRSTLINE_LEADERSHIP';

  return 'NON_TEACHING';
};

